### ISSUE TITLE
engine requirement "^4.2.1" is pretty old, update?

### ISSUE THREAD

**Issue by jaredly** [Khan/react-render-server#3]
could we do `">4.2.1"` or something? I don't even have v4 installed anymore

**Comment by csilvers** [comment]
I guess? -- I don't know why we have it pinned, or what might break if we update.  But feel free to open a pull request!  (Or to change in phabricator.)

**Comment by jlfwong** [comment]
I think it had to do with the version of node available in compute engine at the time we first deployed this

**Comment by ka-role** [comment]
Jamie, I'm not sure I understand this -- don't we install our own node?  In
any case, do you feel comfortable owning this PR?

craig

**Comment by jlfwong** [comment]
We do install our own node, but it looks like the default appengine config used 4.2.1 at the time we first deployed (that's what was generated by `gcloud app gen-config --custom --config=app.yaml`.

Not really comfortable owning it -- I don't have any of this stuff set up, and I'm not using this code for anything personal or for work any more. Just figured I'd chime in for context :)

I think if you change the `>4.2.1`, you'll need to update the Dockerfile too: https://github.com/Khan/react-render-server/blob/master/Dockerfile.prod#L9

**Comment by csilvers** [comment]
OK.  Jared, if you want to make a PR (here or in phabricator), we can try
it out!

craig

**Comment by jaredly** [comment]
Mostly I was trying to use `yarn`, which actually pays attention to the `engines` requirement, and hard fails on install

**Comment by csilvers** [comment]
I updated it to 8.3.
