### ISSUE TITLE
Memory leaks in the use of SSR

### ISSUE THREAD

**Issue by mvcruzata** [Khan/react-render-server#5]
Hi, we have a system in which we set up our websites using SSR, with a flow over 2000 rpm in production environment. Actually, we are facing memory leaks issues by rendering react component throught SSR. We are looking for alternatives for handling SSR efficiently by avoiding possible memory leaks generated by the react compoenents to render. We are evaluating the use of react-render-server as framework for SSR. Have you face similar memory leaks issues before? Does react-render-server have mechanism to avoid those memory leaks? Thank you so much for your support.

**Comment by csilvers** [comment]
I'm sorry, we haven't found memory leaks like that (that I know of!)  We do LRU caching, which may help with memory leaks, but you'd really need to try the product to see if it helped in your situation.
